# Generated by Django 5.1.3 on 2024-11-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
